export { default as SEO } from './SEO'
export { default as CTA } from './CTA'
export { default as Header } from './Header'
export { default as Banner } from './Banner'
export { default as Button } from './Button'
export { default as Quote  } from './Quote'
export { default as Footer } from './Footer'
export { default as Service } from './Service'
export { default as Article } from './Article'
export { default as PageTitle} from './PageTitle'
export { default as ProjectView } from './ProjectView'

export { default as ContactingForm } from './ContactingForm'
export { default as SendingMessage } from './Form/SendingMessage'